import { execFileSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const CURRENT_DIR = dirname(fileURLToPath(import.meta.url));
const PACKAGE_DIR = resolve(CURRENT_DIR, '..');

describe('@base-ui/lit runtime exports', () => {
  it('supports runtime self-reference imports for the package root and switch/input/menu/menubar/popover/preview-card/dialog/alert-dialog/tooltip subpaths', () => {
    const output = execFileSync(
      process.execPath,
      [
        '--input-type=module',
        '-e',
        [
          "const root = await import('@base-ui/lit');",
          "const alertDialogSubpath = await import('@base-ui/lit/alert-dialog');",
          "const autocompleteSubpath = await import('@base-ui/lit/autocomplete');",
          "const calendarSubpath = await import('@base-ui/lit/calendar');",
          "const switchSubpath = await import('@base-ui/lit/switch');",
          "const inputSubpath = await import('@base-ui/lit/input');",
          "const menuSubpath = await import('@base-ui/lit/menu');",
          "const menubarSubpath = await import('@base-ui/lit/menubar');",
          "const popoverSubpath = await import('@base-ui/lit/popover');",
          "const previewCardSubpath = await import('@base-ui/lit/preview-card');",
          "const dialogSubpath = await import('@base-ui/lit/dialog');",
          "const tooltipSubpath = await import('@base-ui/lit/tooltip');",
          "const toggleGroupSubpath = await import('@base-ui/lit/toggle-group');",
          "const comboboxSubpath = await import('@base-ui/lit/combobox');",
          "const contextMenuSubpath = await import('@base-ui/lit/context-menu');",
          "const scrollAreaSubpath = await import('@base-ui/lit/scroll-area');",
          "const tabsSubpath = await import('@base-ui/lit/tabs');",
          "const toolbarSubpath = await import('@base-ui/lit/toolbar');",
          "const drawerSubpath = await import('@base-ui/lit/drawer');",
          "const navigationMenuSubpath = await import('@base-ui/lit/navigation-menu');",
          "const numberFieldSubpath = await import('@base-ui/lit/number-field');",
          "const sliderSubpath = await import('@base-ui/lit/slider');",
          "const selectSubpath = await import('@base-ui/lit/select');",
          "const toastSubpath = await import('@base-ui/lit/toast');",
          "const directionProviderSubpath = await import('@base-ui/lit/direction-provider');",
          "const compositeSubpath = await import('@base-ui/lit/composite');",
          "const cspProviderSubpath = await import('@base-ui/lit/csp-provider');",
          "const labelableProviderSubpath = await import('@base-ui/lit/labelable-provider');",
          "const localizationProviderSubpath = await import('@base-ui/lit/localization-provider');",
          "const temporalAdapterProviderSubpath = await import('@base-ui/lit/temporal-adapter-provider');",
          "const useButtonSubpath = await import('@base-ui/lit/use-button');",
          [
            'process.stdout.write(JSON.stringify({',
            'rootAlertDialog: typeof root.AlertDialogRootElement,',
            'alertDialogSubpath: typeof alertDialogSubpath.AlertDialogRootElement,',
            'rootAutocomplete: typeof root.AutocompleteRootElement,',
            'autocompleteSubpath: typeof autocompleteSubpath.AutocompleteRootElement,',
            'rootCalendar: typeof root.CalendarRootElement,',
            'calendarSubpath: typeof calendarSubpath.CalendarRootElement,',
            'rootSwitch: typeof root.SwitchRootElement,',
            'switchSubpath: typeof switchSubpath.SwitchRootElement,',
            'rootInput: typeof root.InputRootElement,',
            'inputSubpath: typeof inputSubpath.InputRootElement,',
            'rootMenu: typeof root.MenuRootElement,',
            'menuSubpath: typeof menuSubpath.MenuRootElement,',
            'rootMenubar: typeof root.MenubarRootElement,',
            'menubarSubpath: typeof menubarSubpath.MenubarRootElement,',
            'rootPopover: typeof root.PopoverRootElement,',
            'popoverSubpath: typeof popoverSubpath.PopoverRootElement,',
            'rootPreviewCard: typeof root.PreviewCardRootElement,',
            'previewCardSubpath: typeof previewCardSubpath.PreviewCardRootElement,',
            'rootDialog: typeof root.DialogRootElement,',
            'dialogSubpath: typeof dialogSubpath.DialogRootElement,',
            'rootTooltip: typeof root.TooltipRootElement,',
            'tooltipSubpath: typeof tooltipSubpath.TooltipRootElement,',
            'rootToggleGroup: typeof root.ToggleGroupRootElement,',
            'toggleGroupSubpath: typeof toggleGroupSubpath.ToggleGroupRootElement,',
            'rootCombobox: typeof root.ComboboxRootElement,',
            'comboboxSubpath: typeof comboboxSubpath.ComboboxRootElement,',
            'rootContextMenu: typeof root.ContextMenuRootElement,',
            'contextMenuSubpath: typeof contextMenuSubpath.ContextMenuRootElement,',
            'rootScrollArea: typeof root.ScrollAreaRootElement,',
            'scrollAreaSubpath: typeof scrollAreaSubpath.ScrollAreaRootElement,',
            'rootTabs: typeof root.TabsRootElement,',
            'tabsSubpath: typeof tabsSubpath.TabsRootElement,',
            'rootToolbar: typeof root.ToolbarRootElement,',
            'toolbarSubpath: typeof toolbarSubpath.ToolbarRootElement,',
            'rootDrawer: typeof root.DrawerRootElement,',
            'drawerSubpath: typeof drawerSubpath.DrawerRootElement,',
            'rootNavigationMenu: typeof root.NavigationMenuRootElement,',
            'navigationMenuSubpath: typeof navigationMenuSubpath.NavigationMenuRootElement,',
            'rootNumberField: typeof root.NumberFieldRootElement,',
            'numberFieldSubpath: typeof numberFieldSubpath.NumberFieldRootElement,',
            'rootSlider: typeof root.SliderRootElement,',
            'sliderSubpath: typeof sliderSubpath.SliderRootElement,',
            'rootSelect: typeof root.SelectRootElement,',
            'selectSubpath: typeof selectSubpath.SelectRootElement,',
            'rootToast: typeof root.ToastProviderElement,',
            'toastSubpath: typeof toastSubpath.ToastProviderElement,',
            'rootDirectionProvider: typeof root.DirectionProviderElement,',
            'directionProviderSubpath: typeof directionProviderSubpath.DirectionProviderElement,',
            'rootGetDirection: typeof root.getDirection,',
            'directionProviderGetDirection: typeof directionProviderSubpath.getDirection,',
            'rootNavigateList: typeof root.navigateList,',
            'compositeNavigateList: typeof compositeSubpath.navigateList,',
            'rootCSPProvider: typeof root.CSPProviderElement,',
            'cspProviderSubpath: typeof cspProviderSubpath.CSPProviderElement,',
            'rootLabelableProvider: typeof root.LabelableProviderElement,',
            'labelableProviderSubpath: typeof labelableProviderSubpath.LabelableProviderElement,',
            'rootLocalizationProvider: typeof root.LocalizationProviderElement,',
            'localizationProviderSubpath: typeof localizationProviderSubpath.LocalizationProviderElement,',
            'rootTemporalAdapterProvider: typeof root.TemporalAdapterProviderElement,',
            'temporalAdapterProviderSubpath: typeof temporalAdapterProviderSubpath.TemporalAdapterProviderElement,',
            'rootApplyButtonBehavior: typeof root.applyButtonBehavior,',
            'useButtonApplyButtonBehavior: typeof useButtonSubpath.applyButtonBehavior,',
            '}));',
          ].join(' '),
        ].join(' '),
      ],
      {
        cwd: PACKAGE_DIR,
        encoding: 'utf8',
      },
    );

    expect(JSON.parse(output)).toEqual({
      rootAlertDialog: 'function',
      alertDialogSubpath: 'function',
      rootAutocomplete: 'function',
      autocompleteSubpath: 'function',
      rootCalendar: 'function',
      calendarSubpath: 'function',
      rootSwitch: 'function',
      switchSubpath: 'function',
      rootInput: 'function',
      inputSubpath: 'function',
      rootMenu: 'function',
      menuSubpath: 'function',
      rootMenubar: 'function',
      menubarSubpath: 'function',
      rootPopover: 'function',
      popoverSubpath: 'function',
      rootPreviewCard: 'function',
      previewCardSubpath: 'function',
      rootDialog: 'function',
      dialogSubpath: 'function',
      rootTooltip: 'function',
      tooltipSubpath: 'function',
      rootToggleGroup: 'function',
      toggleGroupSubpath: 'function',
      rootCombobox: 'function',
      comboboxSubpath: 'function',
      rootContextMenu: 'function',
      contextMenuSubpath: 'function',
      rootScrollArea: 'function',
      scrollAreaSubpath: 'function',
      rootTabs: 'function',
      tabsSubpath: 'function',
      rootToolbar: 'function',
      toolbarSubpath: 'function',
      rootDrawer: 'function',
      drawerSubpath: 'function',
      rootNavigationMenu: 'function',
      navigationMenuSubpath: 'function',
      rootNumberField: 'function',
      numberFieldSubpath: 'function',
      rootSlider: 'function',
      sliderSubpath: 'function',
      rootSelect: 'function',
      selectSubpath: 'function',
      rootToast: 'function',
      toastSubpath: 'function',
      rootDirectionProvider: 'function',
      directionProviderSubpath: 'function',
      rootGetDirection: 'function',
      directionProviderGetDirection: 'function',
      rootNavigateList: 'function',
      compositeNavigateList: 'function',
      rootCSPProvider: 'function',
      cspProviderSubpath: 'function',
      rootLabelableProvider: 'function',
      labelableProviderSubpath: 'function',
      rootLocalizationProvider: 'function',
      localizationProviderSubpath: 'function',
      rootTemporalAdapterProvider: 'function',
      temporalAdapterProviderSubpath: 'function',
      rootApplyButtonBehavior: 'function',
      useButtonApplyButtonBehavior: 'function',
    });
  });
});
